FROM maven:3.8.1-openjdk-11 AS builder

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package

FROM openjdk:11-jre-slim

COPY --from=builder /app/target/app.jar ./app.jar

ENV APP_PORT=8000

EXPOSE $APP_PORT

CMD ["java", "-jar", "app.jar"]
